//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElDiabloDataAccessLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ElDiabloEntities : DbContext
    {
        public ElDiabloEntities()
            : base("name=ElDiabloEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<RMSFoodItem> RMSFoodItems { get; set; }
        public virtual DbSet<RMSOrder> RMSOrders { get; set; }
        public virtual DbSet<RMSSell> RMSSells { get; set; }
    }
}
