//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElDiabloDataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class RMSOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RMSOrder()
        {
            this.RMSSells = new HashSet<RMSSell>();
        }
    
        public int OrderId { get; set; }
        public string CustomerName { get; set; }
        public string ContactNumber { get; set; }
        public string OrderDate { get; set; }
        public double OrderAmount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RMSSell> RMSSells { get; set; }
    }
}
